//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteCarloAsync.MC2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="opt", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial struct opt : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FoptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] XoptField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Fopt {
            get {
                return this.FoptField;
            }
            set {
                if ((this.FoptField.Equals(value) != true)) {
                    this.FoptField = value;
                    this.RaisePropertyChanged("Fopt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Xopt {
            get {
                return this.XoptField;
            }
            set {
                if ((object.ReferenceEquals(this.XoptField, value) != true)) {
                    this.XoptField = value;
                    this.RaisePropertyChanged("Xopt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MC2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptim", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimResponse")]
        MonteCarloAsync.MC2.opt MonteCarloOptim(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptim", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimResponse")]
        System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimAsync(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptimMolecular", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimMolecularResponse")]
        MonteCarloAsync.MC2.opt MonteCarloOptimMolecular(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptimMolecular", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimMolecularResponse")]
        System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimMolecularAsync(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptimMolecularSeparability", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimMolecularSeparabilityResponse")]
        MonteCarloAsync.MC2.opt MonteCarloOptimMolecularSeparability(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonteCarloOptimMolecularSeparability", ReplyAction="http://tempuri.org/IService1/MonteCarloOptimMolecularSeparabilityResponse")]
        System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimMolecularSeparabilityAsync(int n, int iter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sin", ReplyAction="http://tempuri.org/IService1/SinResponse")]
        double Sin(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sin", ReplyAction="http://tempuri.org/IService1/SinResponse")]
        System.Threading.Tasks.Task<double> SinAsync(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MonteCarloAsync.MC2.CompositeType GetDataUsingDataContract(MonteCarloAsync.MC2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MonteCarloAsync.MC2.CompositeType> GetDataUsingDataContractAsync(MonteCarloAsync.MC2.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MonteCarloAsync.MC2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MonteCarloAsync.MC2.IService1>, MonteCarloAsync.MC2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MonteCarloAsync.MC2.opt MonteCarloOptim(int n, int iter) {
            return base.Channel.MonteCarloOptim(n, iter);
        }
        
        public System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimAsync(int n, int iter) {
            return base.Channel.MonteCarloOptimAsync(n, iter);
        }
        
        public MonteCarloAsync.MC2.opt MonteCarloOptimMolecular(int n, int iter) {
            return base.Channel.MonteCarloOptimMolecular(n, iter);
        }
        
        public System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimMolecularAsync(int n, int iter) {
            return base.Channel.MonteCarloOptimMolecularAsync(n, iter);
        }
        
        public MonteCarloAsync.MC2.opt MonteCarloOptimMolecularSeparability(int n, int iter) {
            return base.Channel.MonteCarloOptimMolecularSeparability(n, iter);
        }
        
        public System.Threading.Tasks.Task<MonteCarloAsync.MC2.opt> MonteCarloOptimMolecularSeparabilityAsync(int n, int iter) {
            return base.Channel.MonteCarloOptimMolecularSeparabilityAsync(n, iter);
        }
        
        public double Sin(double x) {
            return base.Channel.Sin(x);
        }
        
        public System.Threading.Tasks.Task<double> SinAsync(double x) {
            return base.Channel.SinAsync(x);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MonteCarloAsync.MC2.CompositeType GetDataUsingDataContract(MonteCarloAsync.MC2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MonteCarloAsync.MC2.CompositeType> GetDataUsingDataContractAsync(MonteCarloAsync.MC2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
